controller_list:
  - name: fake_arm_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
  - name: fake_gripper_controller
    joints:
      - joint6_1
      - joint6_2