# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - 1
    - 2
    - 3
    - 4
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    Link1
    Link2
    Link3
    Link4
    Link5
    Link6
  gains:
    Link1: {p: 100, i: 0.01, d: 10.0}
    Link2: {p: 100, i: 0.01, d: 10.0}
    Link3: {p: 100, i: 0.01, d: 10.0}
    Link4: {p: 100, i: 0.01, d: 10.0}
    Link5: {p: 100, i: 0.01, d: 10.0}
    Link6: {p: 100, i: 0.01, d: 10.0}